### ISSUE TITLE
Add a wiki: RimWorld Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [IndieWikiBuddy/indie-wiki-buddy-data#144]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://rimworld.fandom.com/wiki/Rimworld_Wiki
Link to destination (independent) wiki: https://rimworldwiki.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
The destination wiki has more content pages (174 vs. 1,551) and is more actively edited than the origin wiki.

**Comment by KevinPayravi** [comment]
Adding in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/83c54a421d316cc377a2fa1e93fb0ef69fbbe945

**Comment by KevinPayravi** [comment]
Now available in version `2.4.0`
