### ISSUE TITLE
Add a wiki: Honkai: Star Rail HoYoWiki

### ISSUE THREAD

**Issue by KevinPayravi** [IndieWikiBuddy/indie-wiki-buddy-data#188]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://honkai-star-rail.fandom.com/wiki/Honkai:_Star_Rail_Wiki
Link to destination (independent) wiki: https://wiki.hoyolab.com/pc/hsr/home

Note from submitter: "HoYoWiki is directly owned by miHoYo"

**Comment by the7thNightmare** [comment]
The destination wiki and the Fandom wiki have a different path for wiki page. The destination uses `/entry` path for each wiki page. I don't know the number after that path is based on what.\
For example, this wiki page in [Fandom](https://honkai-star-rail.fandom.com/wiki/Dan_Heng_%E2%80%A2_Imbibitor_Lunae) and [the destination wiki](https://wiki.hoyolab.com/pc/hsr/entry/1226) is the same character.\
Fandom have 3796 pages and destination have 1479 pages.

**Comment by KevinPayravi** [comment]
Unfortunately not adding for a couple reasons:
* Can't do redirects due to the destination wiki using IDs instead of names in the URL.
* The destination wiki seems to be more of a database, vs. providing articles, so there's a big difference in the nature of coverage.
