### ISSUE TITLE
Add a wiki: Rhythm Doctor

### ISSUE THREAD

**Issue by wolfplay013** [IndieWikiBuddy/indie-wiki-buddy-data#204]
Link to origin wiki: https://rhythm-doctor.fandom.com/wiki/Rhythm_Doctor_Wiki
Link to destination (independent) wiki: https://wiki.rhythm.cafe/page/Main_Page

**Comment by chocmake** [comment]
Seems to be dupe of KevinPayravi/iwb-data#157

**Comment by wolfplay013** [comment]
ah gotcha.
