### ISSUE TITLE
Add a wiki: Warcraft Wiki

### ISSUE THREAD

**Issue by vaisest** [IndieWikiBuddy/indie-wiki-buddy-data#247]
Link to origin wiki: https://wowpedia.fandom.com/wiki/Wowpedia
Link to destination (independent) wiki: https://warcraft.wiki.gg/wiki/Warcraft_Wiki

**Comment by MetalManeMc** [comment]
IWB does not redirect to wiki.gg per it's criteria of independent wikis.
Use [Redirect to wiki.gg](https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca) instead.

**Comment by vaisest** [comment]
I see, thanks for the link.
