### ISSUE TITLE
Add a wiki: Quake WIki

### ISSUE THREAD

**Issue by lavenderdotpet** [IndieWikiBuddy/indie-wiki-buddy-data#262]
Link to fandom wiki: https://quake.fandom.com/wiki/Quake_Wikia
Link to destination (independent) wiki: https://quakewiki.org/wiki/Main_Page

## the fandom wiki is full of inaccurate information and generally has been disliked by the community

**Comment by KevinPayravi** [comment]
Love the Quake Wiki, but this unfortunately won't work well as a redirect. The Fandom wiki (2,805 articles) covers the entire Quake series + spin-offs, while the Quake Wiki (502 articles) is focused on the first game.
