### ISSUE TITLE
Add a wiki: Commander Keen Wiki

### ISSUE THREAD

**Issue by NastyFlytrap** [IndieWikiBuddy/indie-wiki-buddy-data#265]
Link to origin wiki: https://commander-keen.fandom.com/wiki/Commander_Keen_Wiki
Link to destination (independent) wiki: https://keenwiki.shikadi.net/wiki/Main_Page

Thankfully its ranked terribly, atleast on brave search, but still. Fuck fandom

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.2.0` (now available on Chrome, and should be available on Firefox within a few days after review).
