### ISSUE TITLE
Add a wiki: SIGNALIS

### ISSUE THREAD

**Issue by ofsaleem** [IndieWikiBuddy/indie-wiki-buddy-data#302]
Link to origin wiki: https://signalis.fandom.com/wiki/SIGNALIS_Wiki
Link to destination (independent) wiki: https://signalis.wiki.gg/wiki/SIGNALIS_Wiki

**Comment by ofsaleem** [comment]
apologies, i saw that there were instructions on making a PR to do this ourselves, so I went ahead and made a PR https://github.com/KevinPayravi/indie-wiki-buddy/pull/431 for it. that would close this.

**Comment by KevinPayravi** [comment]
Thank you! Now released in `v3.4.0`.
