### ISSUE TITLE
Add a wiki: Against the Storm Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [IndieWikiBuddy/indie-wiki-buddy-data#330]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://against-the-storm.fandom.com
Link to destination (independent) wiki: https://hoodedhorse.com/wiki/Against_the_Storm

**Comment by SnorlaxMonster** [comment]
It appears that [Hooded Horse](https://hoodedhorse.com/) is a indie video game publisher, and they host several wikis for games they have published.

While the games are indie, I'm unsure whether it makes sense to consider wikis hosted by the publisher as "independent". Indie Wiki Buddy includes several official wikis, but my understanding is that those wikis are "official" in the sense that they are endorsed by the IP holder, not that they are owned by them.

The other concern I have is that the site fails to specify a licence. If the community decided to fork from Hooded Horse Wikis to independent hosting, would they be able to (as is the case with CC and GFDL licenced wikis)? Or does Hooded Horse retain the copyright to edits (like Fextralife does)? Based on the "User Content" section of their [terms of use](https://hoodedhorse.com/terms-of-use/), it sounds like editors grant a licence to Hooded Horse to use their content, but do not grant any kind of free or copyleft licence for reusers, implying that forking is not possible. (Licencing is not currently listed in the "criteria for inclusion" for Indie Wiki Buddy, although I think it's an important factor to consider when judging whether a wiki is independent — especially in a case where a wiki is hosted by the owner of the IP the wiki is about.)

**Comment by KevinPayravi** [comment]
I've generally been accepting wikis hosted by the publishers. While not technically independent, they're generally high-quality, have no ads, and are the go-to community resource.

That being said, the lack of a free license is a concern to me too (good eye on catching that!). The wiki is missing both the [general disclaimer](https://hoodedhorse.com/wiki/Against_the_Storm/Against_the_Storm_Official_Wiki:General_disclaimer) and [copyrights](https://hoodedhorse.com/wiki/Against_the_Storm/Against_the_Storm_Official_Wiki:Copyrights) pages that would otherwise usually detail these things.

**Comment by otobot1** [comment]
I'm playing this game right now and I've tried to use both wikis. The fandom one is of very poor quality and I think that a redirect would be worth it in this case despite the license concerns. I can make a pull request - maybe this weekend.

**Comment by SnorlaxMonster** [comment]
For future reference, it appears that Hooded Horse has now added a footer to all of their wikis specifying that they are licenced under CC BY-SA 4.0. ([From Wayback Machine](https://web.archive.org/web/20240601032726/https://hoodedhorse.com/wiki/Against_the_Storm/Against_the_Storm_Official_Wiki), it was added sometime before June 1.)
