### ISSUE TITLE
Add a wiki: Space Pioneers Wiki

### ISSUE THREAD

**Issue by ToxicPea** [IndieWikiBuddy/indie-wiki-buddy-data#532]
Link to origin wiki: https://space-pioneers.fandom.com/wiki/Space_Pioneers_Wiki
Link to destination (independent) wiki: https://spacepioneers.miraheze.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
