### ISSUE TITLE
Add a wiki: ComputerCraft Wiki

### ISSUE THREAD

**Issue by ToxicPea** [IndieWikiBuddy/indie-wiki-buddy-data#538]
Link to origin wiki: https://minecraftcomputercraft.fandom.com/wiki/Minecraft_ComputerCraft_Wiki
Link to destination (independent) wiki: https://www.computercraft.info/wiki/Main_Page

**Comment by KevinPayravi** [comment]
While it's the better source, the computercraft.info wiki appears to be a bit defunct and uneditable. The www.computercraft.info parent site is dead, and the new go-to site for info seems to be tweaked.cc.
