### ISSUE TITLE
Add a wiki: Cherry Forest Wiki

### ISSUE THREAD

**Issue by ToxicPea** [IndieWikiBuddy/indie-wiki-buddy-data#540]
Link to origin wiki: https://cherry-forest.fandom.com/wiki/Cherry_Forest_Wiki
Link to destination (independent) wiki: https://cherryforest.wiki.gg/wiki/Cherry_Forest_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
