### ISSUE TITLE
Add a wiki: Lexicanum

### ISSUE THREAD

**Issue by KevinPayravi** [IndieWikiBuddy/indie-wiki-buddy-data#64]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://warhammer40k.fandom.com/wiki/Warhammer_40k_Wiki
Link to destination (independent) wiki: https://wh40k.lexicanum.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Lexicanum appears to have more content, a dedicated staff to adding more recent content, and also has stricter editing policies (Less fanfic info/inaccuracies with better/more accurate citations) for more quality content.

It is worth noting though that Lexicanum is on an older version of MediaWiki (1.30.0).

**Comment by KevinPayravi** [comment]
Now available in version `2.2.0`
