### ISSUE TITLE
Add a wiki: The Sims Wiki

### ISSUE THREAD

**Issue by VMPYRC** [IndieWikiBuddy/indie-wiki-buddy-data#659]
Link to origin wiki: https://sims.fandom.com/wiki/The_Sims_Wiki
Link to destination (independent) wiki: https://www.thesimswiki.com/wiki/The_Sims_Wiki

**Comment by VMPYRC** [comment]
also related to KevinPayravi/iwb-data#83

**Comment by KevinPayravi** [comment]
Thanks for the submission!

I don't think much has changed since KevinPayravi/iwb-data#83. The wiki's main page itself says to still refer back to the Wikia/Fandom. If the independent wiki closes the coverage gap and can recommend itself as the wiki to use over Fandom, then we can include it.
