### ISSUE TITLE
Add a wiki: The Battle For Wesnoth

### ISSUE THREAD

**Issue by KevinPayravi** [IndieWikiBuddy/indie-wiki-buddy-data#71]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://wesnoth.fandom.com/
Link to destination (independent) wiki: https://wiki.wesnoth.org

**Comment by Elaeagnifolia** [comment]
Destination Wiki has more content pages (~400 vs. ~1400) and content pages are presented well+look quite complete compared to the Fandom Wiki. It also appears to be the official Wiki for the game.

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.7.0` (now available for Chrome, release pending for Firefox).
