### ISSUE TITLE
Add a wiki: Deep Rock Galactic

### ISSUE THREAD

**Issue by eristhea** [IndieWikiBuddy/indie-wiki-buddy-data#78]
Link to origin wiki: https://deeprockgalactic.fandom.com/
Link to destination (independent) wiki: https://deeprockgalactic.wiki.gg/

**Comment by Adrthegamedev** [comment]
Wiki.gg isn't considered independent for this extension; Try https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca (if on firefox, https://addons.mozilla.org/en-US/firefox/addon/redirect-to-wiki-gg/) instead.

**Comment by KevinPayravi** [comment]
I've updated the README with these details as well (the getindie.wiki website said it, but not the README).

**Comment by eristhea** [comment]
thanks!
